CREATE TABLE BOOK
(
    ID           BIGINT PRIMARY KEY NOT NULL,
    PRICE        DOUBLE             NOT NULL,
    TITLE_RU     VARCHAR(255)       NOT NULL,
    TITLE_EN     VARCHAR(255)       NOT NULL,
    FK_AUTHOR_ID BIGINT             NOT NULL
);
CREATE TABLE CATEGORY
(
    ID       BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TITLE_RU VARCHAR(128)       NOT NULL,
    TITLE_EN VARCHAR(128)       NOT NULL
);
CREATE TABLE AUTHOR
(
    ID          BIGINT PRIMARY KEY NOT NULL,
    NAME        VARCHAR(128)       NOT NULL,
    SURNAME     VARCHAR(128)       NOT NULL,
    FK_IMAGE_ID BIGINT
);
CREATE TABLE AUTHOR_IMAGE
(
    ID           BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IMAGE        VARCHAR(255),
    FK_AUTHOR_ID BIGINT
);
CREATE TABLE BOOK_IMAGE
(
    ID         BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    IMAGE      VARCHAR(255),
    FK_BOOK_ID BIGINT
);
CREATE TABLE BASKET
(
    ID         BIGINT PRIMARY KEY NOT NULL,
    FK_USER_ID BIGINT             NOT NULL
);
CREATE TABLE ROLE
(
    ID    BIGINT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(128)       NOT NULL
);
CREATE TABLE USERS
(
    ID           BIGINT PRIMARY KEY NOT NULL,
    EMAIL        VARCHAR(128)       NOT NULL,
    ACTIVE       SMALLINT           NOT NULL,
    USERNAME     VARCHAR(128)       NOT NULL primary key,
    PASSWORD     VARCHAR(60)        NOT NULL,
    FK_ROLE_ID   BIGINT             NOT NULL,
    FK_BASKET_ID BIGINT             NOT NULL
);
ALTER TABLE BOOK
    ADD FOREIGN KEY (FK_AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE;
ALTER TABLE AUTHOR
    ADD FOREIGN KEY (FK_IMAGE_ID) REFERENCES AUTHOR_IMAGE (ID) ON DELETE CASCADE;
ALTER TABLE AUTHOR_IMAGE
    ADD FOREIGN KEY (FK_AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE CASCADE;
ALTER TABLE BOOK_IMAGE
    ADD FOREIGN KEY (FK_BOOK_ID) REFERENCES BOOK (ID) ON DELETE CASCADE;
ALTER TABLE BASKET
    ADD FOREIGN KEY (FK_USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE USERS
    ADD FOREIGN KEY (FK_ROLE_ID) REFERENCES ROLE (ID) ON DELETE CASCADE;
ALTER TABLE USERS
    ADD FOREIGN KEY (FK_BASKET_ID) REFERENCES BASKET (ID) ON DELETE CASCADE;
